apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reflector
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: system
  destination:
    server: https://kubernetes.default.svc
    namespace: reflector
  source:
    repoURL: https://emberstack.github.io/helm-charts
    chart: reflector
    targetRevision: '9.1.22'
    helm:
      valuesObject:
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: null
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
          capabilities:
            drop:
              - ALL
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
