kind: Secret
apiVersion: v1
metadata:
  name: repo-external-secrets
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
  annotations:
    argocd.argoproj.io/sync-wave: "2"
stringData:
  name: external-secrets
  type: helm
  url: https://charts.external-secrets.io
type: Opaque
